tests: Drop test of centos-6
The image cannot be updated, see error below.  In any case we are
testing a RHEL 6 image so it is not really necessary to continue to
test CentOS 6.

Loaded plugins: fastestmirror, security
Setting up Update Process
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
virt-builder: error: yum -y update: command exited with an error

Reviewed-by: Laszlo Ersek <lersek@redhat.com>