Makefile.am: use $(LIBNBD_LIBS) for linking OCaml programs
Otherwise the build fails with errors such as

>   GEN      helper-v2v-output
> /usr/bin/ld: cannot find -lnbd
> collect2: error: ld returned 1 exit status
> File "caml_startup", line 1:
> Error: Error during linking (exit code 1)

in the "convert", "output" and "v2v" modules.

(This patch is similar to guestfs-tools commit 9b0f2e2d5893 ("Makefile.am:
use $(LIBGUESTFS_LIBS) for linking OCaml programs", 2021-09-06).)

Signed-off-by: Laszlo Ersek <lersek@redhat.com>
Message-Id: <20210927063458.4824-2-lersek@redhat.com>
Acked-by: Richard W.M. Jones <rjones@redhat.com>