lib: Add missing <unistd.h> to appliance-uefi.c.
appliance-uefi.c: In function 'guestfs_int_get_uefi':
appliance-uefi.c:67:9: error: implicit declaration of function 'access' [-Werror=implicit-function-declaration]
     if (access (codefile, R_OK) == 0 && access (varsfile, R_OK) == 0) {
         ^~~~~~
appliance-uefi.c:67:5: error: nested extern declaration of 'access' [-Werror=nested-externs]
     if (access (codefile, R_OK) == 0 && access (varsfile, R_OK) == 0) {
     ^~
appliance-uefi.c:67:27: error: 'R_OK' undeclared (first use in this function)
     if (access (codefile, R_OK) == 0 && access (varsfile, R_OK) == 0) {
                           ^~~~
appliance-uefi.c:67:27: note: each undeclared identifier is reported only once for each function it appears in
cc1: all warnings being treated as errors

Fixes commit dd519e8a8ea2be89862f3cec99aff9e19c458afa.