input, output: Use Tools_utils.open_guestfs instead of Guestfs.create
The common function open_guestfs passes verbose and trace flags from
virt-v2v to the libguestfs handle, thus improving debugging.

Also update the common submodule to get:

    mltools: Error out if the libguestfs environment is bad

    Currently setting bogus environment variables causes libguestfs to
    print errors but continue running, eg:

    $ LIBGUESTFS_BACKEND=bogus virt-v2v --version
    libguestfs: error: invalid backend: bogus
    virt-v2v 1.45.96fedora=36,release=1.fc36

    If environment variables are bogus we really ought to exit early
    instead.  After this change:

    $ LIBGUESTFS_BACKEND=bogus virt-v2v --version
    Fatal error: exception Guestfs.Error("invalid backend: bogus")

    Thanks: Xiaodai Wang