rhv-upload: Fix waiting for transfer
We were not considering failures while initializing the transfer. In
this case the transfer phase can change to PAUSED_SYSTEM or
FINISHED_FAILURE, and transfer_url will be None, which failed the
upload with a misleading error:

    RuntimeError: direct upload to host not supported, requires
    ovirt-engine >= 4.2 and only works when virt-v2v is run within the
    oVirt/RHV environment, eg. on an oVirt node

Change the wait loop to consider all cases:
- Transfer failed and was removed
- Transfer failed and will be removed soon
- Transfer paused by the system (cancel required)
- Unexpected transfer phase (cancel required)
- Timeout waiting for TRANSFERRING state (cancel required)

Reported-by: Xiaodai Wang