tests: Drop some obsolete Fedora versions, start testing F35
For very old Fedora versions, it's no longer possible to download the
packages (required by virt-builder --update).  We get this error:

Error: Cannot retrieve metalink for repository: fedora/20/x86_64. Please verify its path and try again

I also dropped Fedora 23 and 29.  Although those can be updated, it's
not really worth testing long-obsolete versions of Fedora.  More
useful is testing the long-term stable equivalents (ie. CentOS and
RHEL).

I did however add the current version of Fedora (35) because it's
worth testing that current Fedora conversions work.

Reviewed-by: Laszlo Ersek <lersek@redhat.com>