rhv-upload: Extract cancel_transfer() function
Extract a cancel_transfer() function, so we can cancel a transfer in
plugin handlers without keeping the transfer_service around.

Fixes a NameError when starting a transfer fails:

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/var/tmp/rhvupload.Vw0CIU/rhv-upload-plugin.py", line 97, in open
        transfer_service.cancel()
    NameError: name 'transfer_service' is not defined

Thanks: Martin Kletzander