ocaml-dep.sh: Add common/mlcustomize to list of directories to search
Avoids this error when you change a file under common/mlcustomize and
then rebuild virt-v2v:

Error: Files ../convert/mlconvert.cmxa
       and ../common/mlcustomize/mlcustomize.cmxa
       make inconsistent assumptions over implementation Inject_virtio_win

Fixes: commit 4b9c8e1560d67ac17e287450f61f4903d237fc47
See-also: commit c30df7ffb8fc04142b99cbb7ec1bebbb32ffb654